CREATE DATABASE CSON DEFAULT CHARSET utf8 COLLATE utf8_general_ci;

USE CSON;

CREATE TABLE USER (
    ID INT(11) AUTO_INCREMENT PRIMARY KEY ,
    USERNAME VARCHAR(50),
    PASSWORD VARCHAR(30),
    PHONENUM VARCHAR(11),
    EMAIL VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ARTICLE (
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(100),
    READERS INT(11),
    CONTENT TEXT,
    IS_SECRET BOOLEAN,
    DATE DATE,
    TAGS VARCHAR(100),
    TYPE VARCHAR(50),
    BRIEF VARCHAR(100)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PERSON_CLASS (
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    CLASS VARCHAR(50)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ARTICLE_TYPE (
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    TYPE VARCHAR(100)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE BLOG_TYPE (
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    TYPE VARCHAR(100)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE RECOMMEND (
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    CONTENT VARCHAR(1000),
    ARTICLE_ID INT(11)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE FOLLOW (
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    FOLLOWED INT(11),
    USER_ID INT(11)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE FAVORITE (
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    ARTICLE_ID INT(11),
    USER_ID INT(11)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE RANKS (
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    RANKS INT(11),
    HITS INT(11),
    SCORES INT(11)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE LOG (
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    LOGIN_DATE DATE,
    USER_ID INT(11)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE UPLOAD (
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50),
    TYPE VARCHAR(50),
    CLASS VARCHAR(50),
    TAGS VARCHAR(100),
    DESCRIPTION VARCHAR(1000),
    URL VARCHAR(100),
    DATE DATE,
    SCORE INT(11),
    USER_ID INT(11)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE SOURCE_TYPE (
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE DOWNLOAD (
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    SOURCE_ID INT(11),
    TIMES INT(11)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE NOTICE (
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(100),
    URL VARCHAR(100),
    DATE DATE,
    IS_READ BOOLEAN,
    USER_ID INT(11)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;